### PR TITLE
feat: implement max_dist_clustering

### LINKED ISSUE #31: How to customize the calculation of clusters?
Google Map cluster API supports custom calculate function to group markers. How can it be possible in this lib?

### PR DESCRIPTION
**Pull request by Babwenbiber**
I implemented a new clustering-approach besides the geohash.
For that I implemented a customized clustering-technique, which is based on the maximum distance of the clusters. You can edit the number of pixels you want your cluster to be (~radius).

I tested that with more than 500 locations onscreen and the performance is still quite good.

Let me know what you think about this and what I have to adjust.

Closes #31

### CODE REVIEW

**Comment by dayron9110** [comment]
News?

**Comment by Babwenbiber** [comment]
I think @bpillon and @buntagonalprism do not maintain this repo anymore?!

P.S. When dealing with a LOT of locations (multiple thousands ONSCREEN) I suggest switching to the old clustering-method. I implemented a threshold config for that in my repo and might update my pull-request once someone interacts here :D

**Comment by fernando-diversius** [comment]
Hopefully this feature gets merged soon.

Thanks for the neat job!

**Comment by dayron9110** [comment]
Any update?

**Comment by Spooky12** [comment]
When will this PR be available on pub.dev?

**Comment by kamami** [comment]
Is there any documentation how to use those new parameters? Any examples?

**Comment by AristideVB** [comment]
Is this PR available ? Any documentation we can help provide ? :)

**Comment by justforworkandstuff** [comment]
@bpillon seems that this PR has already been pushed into master branch. Thinking that you might missed out the pushing of these changes to be reflected onto the pub.dev. Was wondering if there anything you need to assistance with before publishing it to pub.dev? e.g. documentation.

Thanks and have a great day.

**Pull request merged**
