### PR TITLE
Fix issue Newer version has some multiple import variable issue with …

### PR DESCRIPTION
**Pull request by MacDeveloper1**
…latest version of flutter #58

### CODE REVIEW

**Comment by Lerobindesbois** [comment]
Please can you merge this fix as soon as possible :-) Thanks!

**Comment by chawatvish** [comment]
@bpillon please review

**Review by Lerobindesbois — APPROVED** [review]

**Comment by Da1mo** [comment]
Please merge this.. Thanks

**Review by hansvn — APPROVED** [review]

**Comment by hansvn** [comment]
@Lerobindesbois @Da1mo For the time being, you could use the PR in your pubspec:
```
  google_maps_cluster_manager:
    git:
      url: https://github.com/MacDeveloper1/google_maps_cluster_manager.git
      ref: fix/cluster
```

**Comment by AngeloAvv** [comment]
Any updates?

**Comment by sharabiddin** [comment]
LGTM

**Comment by mortenthansen** [comment]
I have created this PR #65 to avoid importing the new Cluster class from the google maps platform interface.

This should fix the issue.

**Comment by a-h-mzd** [comment]
Google Maps is adding clustering support to its Flutter plugin. Maybe that's the reason the author is not spending time on this.

**Comment by a-h-mzd** [comment]
> @a-h-mzd It is great news, where did they share this info?

https://pub.dev/packages/google_maps_flutter_platform_interface/changelog#260

**Comment by bpillon** [comment]
Resolved by #69

**Pull request closed without merging**
